### ISSUE TITLE
Data points vanish on duration changes

### ISSUE THREAD

**Issue by AlexDel** [nagix/chartjs-plugin-streaming#35]
Hello, I'd like to report a bug, But maybe it's a feature and designed behaviour,

After dynamic changing duration from bigger to smaller and to bigger again some points in the beggining of chart dissapears,

It can be repriduced on samle with interactions - https://nagix.github.io/chartjs-plugin-streaming/samples/interactions.html

Steps:
1) Set max duration - 60000 ms
2) Note the first point values
3) Wait a bit - 5-10 seconds.
3) Set min duration - 1000 ms

Actual:
Points that appeared between max and min duration change are lost.

Expected:
All points are preserved.

If you need any help from my side to fix this, please let me know.

**Comment by nagix** [comment]
Thanks for reporting this. Actually, it is the expected behavior - old data is automatically deleted as it disappears off the chart. However, I'm aware that this could be an issue in some use cases.

A possible solution would be introduce the `ttl` property to specify the retention period (if not set, data will be deleted when it disappear). Does this work in your case?

**Comment by AlexDel** [comment]
@nagix  

> A possible solution would be introduce the ttl property to specify the retention period (if not set, data will be deleted when it disappear). Does this work in your case?

Yes, that would be great!

**Comment by nagix** [comment]
I have added the `ttl` property in a69bf28. Set `options.plugins.streaming.ttl` to the retention period in milliseconds.

**Comment by AlexDel** [comment]
@nagix  Thank you! It's very handy
