### ISSUE TITLE
With `pause: true` without setting `ttl`, old data is not removed

### ISSUE THREAD

**Issue by MiniGod** [nagix/chartjs-plugin-streaming#49]
The documentation for `ttl` says:

> If not set, old data will be automatically deleted as it disappears off the chart.

If the chart is paused the old data is not removed. This correct according to the documentation because technically, the data does not disappear off the chart when paused as the chart isn't moving.

However if paused for a long time and there is a lot of new data, and then resuming, the browser can freeze until the old data is removed. This is also bad memory wise.

I expected it to follow the `duration` option (`+ x` to be sure it is off the chart and doesn't affect interpolation), [but appears to be using the scale][call-to-removeOldData]. The scale is not changing when paused.

I'm not sure what the best solution would be. Either way, checking for old data when paused (without having set `ttl`) doesn't do anything useful since `scale.left` doesn't change when paused. So currently that's just wasted cpu.

As a workaround I'm currently setting `ttl` to `duration + 5000`.

_ps: awesome plugin btw. great work_

[call-to-removeOldData]: https://github.com/nagix/chartjs-plugin-streaming/blob/v1.6.1/src/plugins/plugin.streaming.js#L146

**Comment by MiniGod** [comment]
One issue with the workaround is that when `ttl` is set, [backlog is set to 0](https://github.com/nagix/chartjs-plugin-streaming/blob/v1.6.1/src/plugins/plugin.streaming.js#L68) so the chart can get messed up.

**Comment by nagix** [comment]
Thank you for reporting this issue. This is definitely a bug, and I'm considering the following solution:

When the chart is paused,
* if `ttl` is not set, the plugin code removes the data between the right end of the chart and the current time - `duration` - `delay`.
* if `ttl` is set, the plugin code removes the data between the right end of the chart and the current time - `ttl`.

This allows both the visible data and the recent data to be preserved while unnecessary data is removed. It also makes sure to preserve a few data points off the chart so that it doesn't affect interpolation.

**Comment by nagix** [comment]
This change (drawing during pause) was introduced to support per-axis options, but it impacts the cpu usage as you says. Let me think about a better solution on this.

**Comment by nagix** [comment]
I added the check if each scale is paused to decide whether to render the frame in d76c0d6. Now it works the same way as before.
