### ISSUE TITLE
Minimizing page stops streaming

### ISSUE THREAD

**Issue by cythrauL** [nagix/chartjs-plugin-streaming#5]
I'm currently using this plugin to display data I'm polling from a server through ajax.

The asynch ajax method pushes data to an array, and the onRefresh method of the plugin pops it from the array and renders the point.

My problem is that when I minimize the tab, the onRefresh method stops firing (also observable on your demo web-page).

My question (or perhaps feature request) is for the onRefresh method to be called even when the page is minimised.

Can you also recommend a better pattern for using your chart to load datapoints polled from a server through ajax?

**Comment by xarasbir** [comment]
I'm experiencing the same thing. In my case when the tab is not actively viewed, the stream stops.

**Comment by nagix** [comment]
The current version is using `requestAnimationFrame()` for both rendering and calling the `onRefresh()`, so `onRefresh()` won't be called if the tab is minimized as you mentioned. The workaround would be storing metrics data and the cursor position, and when `onRefresh()` is called, rendering all the new points since the previous `onRefresh()` call based on the cursor position.

Anyway, it might be a good idea to use `setInterval()` which is called even when the tab is minimized. Thanks for your feedback.

**Comment by nagix** [comment]
I have added support for background `onRefresh()` calls using `setInterval()` with 9951cd1.
See this sample: https://jsfiddle.net/nagix/yvwqm5no/
